#pragma once
#include <fstream>
#include <iostream>
#include <iomanip>
#include <cstdlib>
#include <string>
#include "user.h"
#include "register.h"
#include "find.h"
#include "error.h"
#include <windows.h>
#include "list.h"
#include "utils.h"