#pragma once
#include <fstream>
#include <iostream>
#include <iomanip>
#include <cstdlib>
#include <algorithm>
#include <vector>
#include <string>
#include "user.h"
#include "auth.h"
#include "find.h"
#include "error.h"
#include <conio.h>
#include <windows.h>
#include "list.h"
#include "utils.h"
#include "global.h"